### ISSUE TITLE
Can I use it in WPF?

### ISSUE THREAD

**Issue by assopri** [arklumpus/MDEdit#1]
Can I use it in WPF .NET project, not Avalonia?

**Comment by arklumpus** [comment]
Hi, no, I don't think this is possible ☹

If you really want to, it should not be too hard to transform your application so that it uses Avalonia instead of WPF, but you should see if it's worth it.

However, if you just want to render Markdown documents, (rather than having full editor capabilities), you might want to look at [VectSharp.Markdown](https://github.com/arklumpus/VectSharp/tree/master/VectSharp.Markdown). You can use this together with VectSharp.SVG to produce SVG files; otherwise it might be relatively easy to implement an output layer for VectSharp that uses System.Drawing or directly WPF controls...
